services:
  # Your Website (High performance Nginx Alpine)
  my-website:
    image: nginx:alpine
    container_name: web_server
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html

  # The Tunnel Agent (The bridge to the internet)
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_tunnel
    restart: always
    command: tunnel run --token YOUR_CLOUDFLARE_TOKEN_HERE
